### ISSUE TITLE
Calling unknown method: app\models\xxxSearch::joinWithRelation()

### ISSUE THREAD

**Issue by arjenmeijer** [codiverum/yii2-relation-search-filter#1]
Thanks for publishing this code, but ....

I follow the instructions and I get:

Unknown Method – yii\base\UnknownMethodException
Calling unknown method: app\models\xxxSearch::joinWithRelation()

In the documentation the paths are:
readme: use \codiverum\relationSF\RelationSFTrait; (notice the \ in front)
in the code:  use codiverum\relationSF\RelationSFTrait;

In the filesystem the path is: codiverum/yii2-relation-search-filter\RelationSFTrait; (notice the different name of SF=-.search-filter)

So, please correct the readme and the path in the filesystem. - is not allow in Yii2 -> syntax error, unexpected '-', expecting ',' or ';'

And even than, I can not get this to work. Mmmmm, something is missing.

**Comment by codevalar** [comment]
Thanks for pointing this out. I'll correct it ASAP

**Comment by codevalar** [comment]
I corrected trait instruction.
There should be no error with name `yii-relation-search-filter`. Dash is allowed in Yii2. More than that - Gii encourages you to name your extension using dash convention.

Your error is a result of missing `\` in `use` statement.

**Comment by arjenmeijer** [comment]
Thanks, I will try it again.

**Comment by arjenmeijer** [comment]
This is what I do with version 1.05:

in the search model ->
namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Gebeurtenis;
use \codiverum\relationSF\RelationSFTrait;

class GebeurtenisSearch extends Gebeurtenis
{
    public $plaats;
        ....

```
public function search($params)
{
    $query = Gebeurtenis::find();
$this->joinWithRelation($query, 'plaats');
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
    ]);
$this->addRelationSort($dataProvider, 'plaats', 'plaatsomschrijving', 'tbl_plaats');
    $this->load($params);
    if (!$this->validate()) {
        // uncomment the following line if you do not want to return any records when validation fails
        // $query->where('0=1');
        return $dataProvider;
    }
    $query->andFilterWhere([
        'gebeurtenis_id' => $this->gebeurtenis_id,
        ....
        'updated_by' => $this->updated_by,
    ]);
    $query->andFilterWhere(['like', 'samenvatting', $this->samenvatting])
       ...
        ->andFilterWhere(['like', 'url', $this->url]);
$this->addRelationFilter($query, 'plaats', 'plaatsomschrijving', 'tbl_plaats');
    return $dataProvider;
}
```

This code give me:
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: app\models\GebeurtenisSearch::joinWithRelation()

**Comment by codevalar** [comment]
I see the problem. According to readme (generally you always use traits like this) you have to put the use statement inside the body of the class. Like this:

``` php
class XxxSearch extends Xxx {
  use \codiverum\relationSF\RelationSFTrait;
...
}
```

**Comment by arjenmeijer** [comment]
Thanks!! It works wonderful now.

**Comment by codevalar** [comment]
Happy to help :)

**Comment by arjenmeijer** [comment]
Has a relation with a viaTable the same construction?

**Comment by codevalar** [comment]
I haven't tested it, but I think there may be a problem if you will try to use aliases it may not work.
Without aliases models code probablyl will work but in the view `value` should be different because `viaTable` is many-to-many type of relation so there is not single one related record. I guess in the view should be sth like this:

``` php
[
  'attribute' =>  `realtion_name`,
  'value' => function($data) { 
    //print first value or implode names or do whatever you need
  },
]
```

I'll try to test when I have a moment.
